
version: "3.4"

services:
  restaurant.tests.sql:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  restaurant.tests.eventstore:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  restaurant.tests:
    image: restauranttests
    build:
      context: ./server
      dockerfile: ./tests/Restaurant.Business.Tests/Dockerfile
    depends_on:
      - restaurant.tests.sql
      - restaurant.tests.eventstore
    links:
      - restaurant.tests.sql:relationaldb
      - restaurant.tests.eventstore:eventstore
    volumes:
      - ./:/coverage